### PR TITLE
Typos, grammar and style

### PR DESCRIPTION
**Pull request by NicoWeio**
I used [GPT-3.5](https://chat.openai.com/) to generate suggestions for the improvement of text within this repo, which I then manually verified.

### CODE REVIEW

**Comment by rmadar** [comment]
Sounds good to me ! Is there a reason to still have this PR *work in progress* ?

**Comment by NicoWeio** [comment]
Thanks! Due to the manual checking and copy-paste actions involved, I did not yet manage to cover the whole repository. With further automation, I should be able to complete this relatively soon, though.

**Comment by rmadar** [comment]
OK perfect. But there is no hurry ... so this dont make this a priority. Also, just to let you know, I am updating the chapter 2 notebook in the meanwhile.

**Comment by NicoWeio** [comment]
I now used AI (GitHub Copilot Chat) to generate a Python script that asks `gpt-3.5-turbo` to improve each Markdown cell. Then, I simply went through and verified the correctness of all changes. 
Because of the huge number of changes, I might have missed some errors, both in the original and in the AI-modified versions.
I might touch-up the assignments, exercises, and exams in another PR in the future, once I have found a good way to modify the solutions at the same time, and once I have even more time to spare. :)
For full transparency, I paid $0.16 for the OpenAI API calls. Below is the _system prompt_ I used.
<details>
<summary>Prompt</summary>

```
- Fix grammar and spelling errors in this Markdown cell.
    - Pay attention to the correct case: NumPy etc.
- Do not add or rewrite content beyond fixing errors! Stylistic improvement of single words/phrases is fine.
    - Math should be left alone.
    - Do not make titles title-case.
    - Do not change colons to periods at the end of the cell.
- Make lists use dashes.
- Single-digit numbers should NOT be modified to be spelled out.
- If you spot errors in the meaning (such as off-by-one), write them in a TODO comment (HTML) at the end of the cell.
- Do not write anything else before or after the cell content.
```

</details>

**Comment by rmadar** [comment]
Thanks a lot for the contribution, that's appreciated ! Cheers !

**Pull request merged**
